version: '3.8'
services:
  discovery-server:
    build:
#      context: ./discovery-server
      dockerfile: discovery-server/Dockerfile
    container_name: discovery-server
    ports: ['8761:8761']
    networks:
      - backend

  postgres-users:
    image: 'postgres:15-alpine'
    container_name: postgres-users
    restart: always
    environment:
      POSTGRES_DB: sky_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ['5432:5432']
    volumes:
      - pgdata:/var/lib/postgresql/sky_users
    networks:
      - backend

  gateway:
    build:
#      context: ./gateway
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
      SPRING_SECURITY_JWT_SECRET: '${SPRING_SECURITY_JWT_SECRET}'
    ports: ['8080:8080']
    networks:
      - backend

  user-service:
    build:
#      context: ./user-service
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      - discovery-server
      - postgres-users
    environment:
      SPRING_DATASOURCE_URL: '${SPRING_DATASOURCE_URL}'
      SPRING_DATASOURCE_USERNAME: '${SPRING_DATASOURCE_USERNAME}'
      SPRING_DATASOURCE_PASSWORD: '${SPRING_DATASOURCE_PASSWORD}'
      SPRING_SECURITY_JWT_SECRET: '${SPRING_SECURITY_JWT_SECRET}'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports: ['8081:8081']
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  pgdata:
    driver: local